### ISSUE TITLE
Is "make python" still work?

### ISSUE THREAD

**Issue by FrankRouter** [JohnLangford/vowpal_wabbit#1036]
```
./autogen.sh
make
```
Works fine and the vw binary is OK. But `make python` seems broken.
```
make python
/usr/bin/make64 MAC=64 python
make64: Nothing to be done for `python'.
```
While "Nothing to be done", pylibvw.so is not compiled.

**Comment by pommedeterresautee** [comment]
You are supposed to install it through pip (even local code)

**Comment by gramhagen** [comment]
```make python``` should still work (you can always try to force it with ```make -B python```, though @pommedeterresautee is right, I think it's preferable to pip install the local version if you are interested in the python binding

```pip install -e python```

from the main vowpal_wabbit directory

and then in python:
```
from vowpalwabbit import pyvw
pyvw.vw()
```

**Comment by FrankRouter** [comment]
`make -B python` does not work. pylibvw.so is not compiled.
```
make -B python
...
config.status: executing depfiles commands
config.status: executing libtool commands
make64: Nothing to be done for `python'.
```
`pip install vowpalwabbit` works for me. But I'd like to tweak the python interface for some reason, so makefile is a problem now.
`pip install -e python` does not work neither.
```
pip install -e python/ --root=~/local_install/
Obtaining file:///home/vw/github/vowpal_wabbit/python
Installing collected packages: vowpalwabbit
  Running setup.py develop for vowpalwabbit
    Complete output from command /home/vw/.linuxbrew/Cellar/python/2.7.11/bin/python -c "import setuptools, tokenize;__file__='/home/vw/github/vowpal_wabbit/python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing vowpalwabbit.egg-info/PKG-INFO
    writing top-level names to vowpalwabbit.egg-info/top_level.txt
    writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.exe' found anywhere in distribution
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    running build_ext
    /usr/bin/make64 MAC=64 python
    CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/vw/github/vowpal_wabbit/missing aclocal-1.15 -I acinclude.d
    aclocal-1.15: warning: couldn't open directory 'acinclude.d': No such file or directory
     cd . && /bin/sh /home/vw/github/vowpal_wabbit/missing automake-1.15 --foreign
    configure.ac:2: error: required file 'vowpalwabbit/config.h.in' not found
    configure.ac:76: error: required file 'vowpalwabbit/Makefile.in' not found
    configure.ac:76: error: required file 'cluster/Makefile.in' not found
    Makefile.am:1: error: required directory ./vowpalwabbit does not exist
    Makefile.am:1: error: required directory ./cluster does not exist
    make64: *** [Makefile.in] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/vw/github/vowpal_wabbit/python/setup.py", line 184, in <module>
        tests_require=['tox'],
      File "/home/vw/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/vw/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/vw/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/vw/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/vw/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/setuptools/command/develop.py", line 119, in install_for_development
        self.run_command('build_ext')
      File "/home/vw/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/vw/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/vw/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 66, in run
        _build_ext.run(self)
      File "/home/vw/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/vw/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "/home/vw/github/vowpal_wabbit/python/setup.py", line 102, in build_extension
        subprocess.check_call(['make', 'python'], cwd=path.join(here, 'src'), env=env)
      File "/home/vw/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'python']' returned non-zero exit status 2

    ----------------------------------------
Command "/home/vw/.linuxbrew/Cellar/python/2.7.11/bin/python -c "import setuptools, tokenize;__file__='/home/vw/github/vowpal_wabbit/python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/vw/github/vowpal_wabbit/python/
```

**Comment by arielf** [comment]
Could this be an issue with the auto-generated Makefile (by autogen.sh)?

When I try on Ubuntu, where I always avoid running `autogen.sh`, it uses the original `Makefile` from the repo, and things seem to work just fine:

```
$ make python
cd vowpalwabbit; make -j 8 things
make[1]: Entering directory '.../src/vowpal_wabbit/arielf/vowpalwabbit'
make[1]: Nothing to be done for 'things'.
make[1]: Leaving directory '.../src/vowpal_wabbit/arielf/vowpalwabbit'
cd python; make things
make[1]: Entering directory '.../src/vowpal_wabbit/arielf/python'
Using Python 2.7
/usr/bin/g++ -std=c++0x -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I /usr/include -fPIC -c pylibvw.cc -o pylibvw.o
/usr/bin/g++ -shared -Wl,--export-dynamic pylibvw.o -L /usr/local/lib -L /usr/lib -L /usr/lib/x86_64-linux-gnu -L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions ../vowpalwabbit/libvw.a ../vowpalwabbit/liballreduce.a -L /usr/local/lib -L /usr/lib -L /usr/lib/x86_64-linux-gnu -l boost_program_options -l pthread -l z -l boost_python -o pylibvw.so
make[1]: Leaving directory '.../src/vowpal_wabbit/arielf/python'

# Try again:

$ make python
cd vowpalwabbit; make -j 8 things
make[1]: Entering directory '.../src/vowpal_wabbit/arielf/vowpalwabbit'
make[1]: Nothing to be done for 'things'.
make[1]: Leaving directory '.../src/vowpal_wabbit/arielf/vowpalwabbit'
cd python; make things
make[1]: Entering directory '.../src/vowpal_wabbit/arielf/python'
make[1]: Nothing to be done for 'things'.
make[1]: Leaving directory '.../src/vowpal_wabbit/arielf/python'
```

**Comment by FrankRouter** [comment]
Yes. It is autogen.sh. By the way, I check the pip install log, make sure that only `make python` is executed. That's why pip install works well. Thanks. @arielf

**Comment by lockie** [comment]
I have an exact stack trace as in [this comment](https://github.com/JohnLangford/vowpal_wabbit/issues/1036#issuecomment-232841078) for both stock and autogenerated `Makefile`. I'm using Gentoo and Python 3.5. How do I fix this?..

**Comment by gramhagen** [comment]
Typically I move to the python directory and run 'python3 setup.py install'

You might try 'python3 setup.py clean' first

**Comment by lockie** [comment]
@gramhagen Thanks!
I've solved it by simply installing vw from pip though.
