### ISSUE TITLE
Problem with pip install vowpalwabbit

### ISSUE THREAD

**Issue by 5kyn37** [JohnLangford/vowpal_wabbit#1174]
Hello.
I have CentOS release 6.8 (Final), python version 2.7.8 and boost library 1.5.9.

```bash
pip install vowpalwabbit
...
    copying vowpalwabbit/sklearn_vw.py -> build/lib.linux-x86_64-2.7/vowpalwabbit
    running egg_info
    creating vowpalwabbit.egg-info
    writing vowpalwabbit.egg-info/PKG-INFO
    writing top-level names to vowpalwabbit.egg-info/top_level.txt
    writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'src'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.exe' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    running build_ext
    make: *** No rule to make target `clean'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jmdvzz/vowpalwabbit/setup.py", line 188, in <module>
        tests_require=['tox'],
      File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/user/pr/venv/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/user/pr/venv/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
        self.build_extension(ext)
      File "/tmp/pip-build-jmdvzz/vowpalwabbit/setup.py", line 98, in build_extension
        prep()
      File "/tmp/pip-build-jmdvzz/vowpalwabbit/setup.py", line 57, in prep
        subprocess.check_call(['make', 'clean'], cwd=path.join(here, 'src', 'python'))
      File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'clean']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/home/user/pr/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jmdvzz/vowpalwabbit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-a3xDXp-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/pr/venv/include/site/python2.7/vowpalwabbit" failed with error code 1 in /tmp/pip-build-jmdvzz/vowpalwabbit/
''' 
I have seen this issue: https://github.com/JohnLangford/vowpal_wabbit/issues/1021, but I have boost version greater than 1.5.4 .

**Comment by arielf** [comment]
Looks like you're missing build prerequisites (make, etc.) needed by `pip install`

**Comment by arielf** [comment]
`make` is complaining on missing `clean` target.
I can't reproduce this on Ubuntu 16.04.1. Here's the full session.

```
$ pip install vowpalwabbit
Collecting vowpalwabbit
  Downloading vowpalwabbit-8.2.1.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 1.4MB/s
Building wheels for collected packages: vowpalwabbit
  Running setup.py bdist_wheel for vowpalwabbit ... done
  Stored in directory: /home/ariel/.cache/pip/wheels/90/39/f7/c9c67661b119ad0dad7570526c84a5a4601ef7c2c6f11d2c51
Successfully built vowpalwabbit
Installing collected packages: vowpalwabbit
Successfully installed vowpalwabbit-8.2.1
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Looks like something is missing in your env, but hard to tell what it is from the provided output.

**Comment by arielf** [comment]
Digging deeper into this.
Looks like there are two separate/incompatible python packaging systems. The old is called 'egg', the new is called 'whl' (extension stands for wheels)

> Wheels are the new standard of python distribution and are intended to replace eggs.
> Support is offered in pip >= 1.4 and setuptools >= 0.8 .

The new (wheels) method seems to works smoothly with the relatively new/current vowpalwabbit packages. 

When you're running `pip` in this CentOS env you seem to be using (very) old `egg`.  Perhaps you should look at building everything on Ubuntu and using precompiled binaries and/or a docker (or similar image) package isolating you from the old env you have.  For `vw` at least, I've been using precompiled statically linked binaries whenever I need to run on RHEL/CentOS. I found these too painful use as development/build environments.

I have it on my TODO list to publish a docker file for `vw`. Stay tuned.

**Comment by 5kyn37** [comment]
When I try to build from github repo without virtualenv.

```
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/vowpalwabbit
copying vowpalwabbit/__init__.py -> build/lib.linux-x86_64-2.7/vowpalwabbit
copying vowpalwabbit/pyvw.py -> build/lib.linux-x86_64-2.7/vowpalwabbit
copying vowpalwabbit/sklearn_vw.py -> build/lib.linux-x86_64-2.7/vowpalwabbit
running egg_info
creating vowpalwabbit.egg-info
writing vowpalwabbit.egg-info/PKG-INFO
writing top-level names to vowpalwabbit.egg-info/top_level.txt
writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'src'
warning: no files found matching '*.dll' under directory 'bin'
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.exe' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
running build_ext
rm -f *.o pylibvw.so
cd .. && make  am--refresh
make[1]: Entering directory `/home/user/vowpal_wabbit/python/src'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/user/vowpal_wabbit/missing --run aclocal-1.11 -I acinclude.d
aclocal-1.11: couldn't open directory `acinclude.d': No such file or directory
make[1]: *** [aclocal.m4] Error 1
make[1]: Leaving directory `/home/user/vowpal_wabbit/python/src'
make: *** [../aclocal.m4] Error 2
Traceback (most recent call last):
  File "setup.py", line 202, in <module>
    tests_require=['tox']
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/build_ext.py", line 52, in run
  File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
    self.build_extension(ext)
  File "setup.py", line 98, in build_extension
    prep()
  File "setup.py", line 67, in prep
    subprocess.check_call(['make', 'clean'], cwd=path.join(here, 'src', folder))
  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'clean']' returned non-zero exit status 2
```
what is more

```
[10:01][root.server: python]# vw --he
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
Error: unrecognised option '--he'

finished run
number of examples = 0
weighted example sum = 0
weighted label sum = 0
average loss = -nan
total feature number = 0
vw: unrecognised option '--he'
```
console version has been compiled successfully.

**Comment by 5kyn37** [comment]
Well, Perhaps I can see another variant. I would like to hear your opinion on this issue. The situation is such that I need to solve the problem of binary classification. It must be an online learning. I need to predict a probability of Class A. I need to work with unbalanced data (~1:500 or ~1:1000). Ratio of element's numbers of class A to class B may change significantly over time. It happened so I write code on a python. Vw is able to learn and make predictions in daemon mode. I want to focus my training on the boundary cases only (details can be found [there](http://stackoverflow.com/questions/24634602/how-to-perform-logistic-regression-using-vowpal-wabbit-on-very-imbalanced-datase)). First, I want to receive a response from the predictor. If I wouldn't be satisfied with the accuracy of prediction, the predictor will take into account this example in the following prediction. In order to realize such a scenario, I need a few models and demons, right? Let me explain. At least two daemons should be run in parallel. Demons have been initialized with the same model. The first daemon is running in prediction mode (without learning), the second daemon is capable of learning. Every time I ask the opinion of the first daemon. If the first daemon made a significant mistake in the prediction, then I teach second daemon on this example. By schedule (every n minutes or hours or days) online training stops for a few seconds and both daemon restart with uplearning model.

**Comment by arielf** [comment]
- On the build issue: same comment as above. It is using 'egg'.
- On the '--he` issue: the option is `--help`
- On the question on how to do unbalanced binary classification: yes doing active learning seems reasonable. There's an example `active_interactor.cc` in the source tree which can help in active learning.
- Not sure why you need two daemons. I think one suffices. you can learn while making predictions.  If you want a prediction without modifying the in-memory model, you can use a weight of 0 to the example. Saving the model to disk can be done periodically by sending the "save" string to the daemon (see `process_example` function in `vowpalwabbit/learner.cc`.

**Comment by 5kyn37** [comment]
Thank you. Your answer helped.
