### ISSUE TITLE
Install vowpalwabbit python wrapper problems

### ISSUE THREAD

**Issue by andrei-kondakov** [JohnLangford/vowpal_wabbit#1220]
Hi, 

I try to install  vowpalwabbit python's wrapper.

After exectution:
```
  $ brew install libtool autoconf automake
  $ brew install boost-python --with-python3
  $ pip install vowpalwabbit
```

I got following error:
```
Using Python 3.6
/usr/bin/g++ -std=c++0x -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I /usr/local/include -I ../rapidjson/include -fPIC -c pylibvw.cc -o pylibvw.o
/usr/bin/g++ -shared  pylibvw.o -L /usr/local/lib -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation ../vowpalwabbit/libvw.a ../vowpalwabbit/liballreduce.a -L /usr/local/lib -lboost_program_options-mt -lboost_serialization-mt -l pthread -l z -l boost_python3-mt -o pylibvw.so
Undefined symbols for architecture x86_64:
"boost::python::detail::init_module(char const*, void (*)())", referenced from:
    _initpylibvw in pylibvw.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [pylibvw.so] Error 1
make: *** [python] Error 2
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/private/var/folders/n6/lhgdgsns3z5gh0q93s3w_dz80000gn/T/pip-build-lesezaxg/vowpalwabbit/setup.py", line 202, in <module>
  tests_require=['tox']
File "/Users/andrei/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
  dist.run_commands()
File "/Users/andrei/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
  self.run_command(cmd)
File "/Users/andrei/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
  cmd_obj.run()
File "/Users/andrei/anaconda/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
  self.run_command('build')
File "/Users/andrei/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
  self.distribution.run_command(command)
File "/Users/andrei/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
  cmd_obj.run()
File "/Users/andrei/anaconda/lib/python3.6/distutils/command/build.py", line 135, in run
  self.run_command(cmd_name)
File "/Users/andrei/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
  self.distribution.run_command(command)
File "/Users/andrei/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
  cmd_obj.run()
File "/Users/andrei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/build_ext.py", line 77, in run
File "/Users/andrei/anaconda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
  _build_ext.build_ext.run(self)
File "/Users/andrei/anaconda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
  self.build_extensions()
File "/Users/andrei/anaconda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
  self.build_extension(ext)
File "/private/var/folders/n6/lhgdgsns3z5gh0q93s3w_dz80000gn/T/pip-build-lesezaxg/vowpalwabbit/setup.py", line 113, in build_extension
  subprocess.check_call(['make', 'python'], cwd=path.join(here, 'src'), env=env)
File "/Users/andrei/anaconda/lib/python3.6/subprocess.py", line 291, in check_call
  raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'python']' returned non-zero exit status 2.
``` 

I try to run this command with include and exclude anaconda bin from PATH and still got this exeception.

What I am doing wrong?

P.S. full log: [vw_pip_install_log.txt](https://github.com/JohnLangford/vowpal_wabbit/files/888518/vw_pip_install_log.txt)

**Comment by JohnLangford** [comment]
I'm not sure.  @gramhagen any ideas?

**Comment by Scott-Graham-Bose** [comment]
are using pip from within anaconda? it looks like that from the directory name (anaconda/bin/pip).

if this is the case it will still try to use anaconda boost libraries which will cause difficulties. you need to use a separate installation of python and pip.

**Comment by andrei-kondakov** [comment]
@Scott-Graham-Bose  I am trying to install vowal_wabbit on clean installed OS X.

```
 $ brew install libtool autoconf automake
 $ brew install boost-python --with-python3
 $ pip install vowpalwabbit
```

And get the same error in 

```
Using Python 3.6
  /usr/bin/g++ -std=c++0x -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I /usr/local/include -I ../rapidjson/include -fPIC -c pylibvw.cc -o pylibvw.o
  /usr/bin/g++ -shared  pylibvw.o -L /usr/local/lib -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation ../vowpalwabbit/libvw.a ../vowpalwabbit/liballreduce.a -L /usr/local/lib -lboost_program_options-mt -lboost_serialization-mt -l pthread -l z -l boost_python3-mt -o pylibvw.so
  Undefined symbols for architecture x86_64:
    "boost::python::detail::init_module(char const*, void (*)())", referenced from:
        _initpylibvw in pylibvw.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[1]: *** [pylibvw.so] Error 1
  make: *** [python] Error 2
.....
....  
.... 
subprocess.CalledProcessError: Command '['make', 'python']' returned non-zero exit status 2.
```

[full_log](https://github.com/JohnLangford/vowpal_wabbit/files/916700/wv.pdf)

Is it okay to use python 3.6 and not 3.5?

**Comment by Scott-Graham-Bose** [comment]
yeah, there's a common theme with the python libs getting mixed up during the build.

can you tell me what you get back with these commands?
```
python3.6-config --includes
python3.6-config --ldflags
```

**Comment by andrei-kondakov** [comment]
@Scott-Graham-Bose sure:

```
➜  ~ python3.6-config --includes
-I/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/include/python3.6m
➜  ~ python3.6-config --ldflags
-L/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation
```

**Comment by Scott-Graham-Bose** [comment]
Please review #1208 for solutions, we need to pull them in and push to pypi before this can be resolved through pip. until then you will need to clone the repo and make some modifications to the python makefile.

**Comment by andrei-kondakov** [comment]
Changing the Makefile in the python directory working for me:

```
ifeq ($(VIRTUAL_ENV), )
  PYTHON_INCLUDE = $(shell python$(PYTHON_VERSION)-config --includes)
  PYTHON_LDFLAGS = $(shell python$(PYTHON_VERSION)-config --ldflags)
else
  PYTHON_INCLUDE = $(shell python-config --includes)
  PYTHON_LDFLAGS = $(shell python-config --ldflags)
endif

```
to this:

```
PYTHON_INCLUDE = $(shell python$(PYTHON_VERSION)-config --includes)
PYTHON_LDFLAGS = $(shell python$(PYTHON_VERSION)-config --ldflags)
```

@Scott-Graham-Bose Thanks for the solution.

**Comment by JohnLangford** [comment]
Closing, looks like this is resolved.  Thanks all.
