### ISSUE TITLE
Multithread issues

### ISSUE THREAD

**Issue by hsinyij** [JohnLangford/vowpal_wabbit#1265]
Hi,

I am new to VW but we have a project which needs to use VW for prediction (with shared model, i.e., one .vw file). I install the Nuget package version 8.3.0.9. The scenario is, for each request to our service, we will process it in multiple thread in parallel. We only initialize one vwModel in the constructor by

        private readonly VowpalWabbitModel vwModel;
        private readonly VowpalWabbitThreadedPrediction modelPool;

        public ClassName(string vwModelFileName)
        {
            vwModel = new VowpalWabbitModel("-i " + vwModelFileName);
            modelPool = new VowpalWabbitThreadedPrediction(vwModel);
        }

The following function is called in each thread

        public float GetPredict(string text)
        {
            using (var vw = modelPool1.GetOrCreate())
            {
                return vw.Value.Predict(text, VowpalWabbitPredictionType.Scalar);
            }
        }

I use Visual Studio to run the functional test. At beginning, the several tests passed, but later the tests failed because of the file lock is not released by previous execution (I keep the test execution engine running in test settings) and therefor the bad model format exception was thrown. The following is the exception:

Result StackTrace:	
at VW.VowpalWabbitBase..ctor(VowpalWabbitSettings settings) in d:\a\1\s\cs\cli\vw_base.cpp:line 92
   at VW.VowpalWabbit..ctor(VowpalWabbitSettings settings) in d:\a\1\s\cs\cli\vowpalwabbit.cpp:line 28
   at VW.VowpalWabbitThreadedPredictionBase`1.CreateVowpalWabbitChild(VowpalWabbitModel model) in D:\a\1\s\cs\cs\VowpalWabbitThreadedPredictionBase.cs:line 63
   at VW.VowpalWabbitThreadedPredictionBase`1.<.ctor>b__3_0(VowpalWabbitModel m) in D:\a\1\s\cs\cs\VowpalWabbitThreadedPredictionBase.cs:line 52
   at VW.ObjectPool`2.GetOrCreate() in D:\a\1\s\cs\cs\ObjectPool.cs:line 152
...
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> VW.VowpalWabbitException: bad model format!

Here I got a question: It seems that the deconstructor/dispose has some issues to leave the file lock still open after the test execution is done. Is that true?

If I move the modelPool from constructor to the function GetPredict as follows: 

        public float GetPredict(string text)
        {
            using (var modelPool1 = new VowpalWabbitThreadedPrediction(vwModel))
            using (var vw = modelPool1.GetOrCreate())
            {
                return vw.Value.Predict(text, VowpalWabbitPredictionType.Scalar);
            }
        }

I got the following exception:

   at VW.seed_vw_model(vw* , basic_string<char\,std::char_traits<char>\,std::allocator<char> >* , IntPtr , Void* )
   at VW.VowpalWabbitBase..ctor(VowpalWabbitSettings settings) in d:\a\1\s\cs\cli\vw_base.cpp:line 66
   at VW.VowpalWabbit..ctor(VowpalWabbitSettings settings) in d:\a\1\s\cs\cli\vowpalwabbit.cpp:line 28
   at VW.VowpalWabbitThreadedPredictionBase`1.CreateVowpalWabbitChild(VowpalWabbitModel model) in D:\a\1\s\cs\cs\VowpalWabbitThreadedPredictionBase.cs:line 63
   at VW.VowpalWabbitThreadedPredictionBase`1.<.ctor>b__3_0(VowpalWabbitModel m) in D:\a\1\s\cs\cs\VowpalWabbitThreadedPredictionBase.cs:line 52
   at VW.ObjectPool`2.GetOrCreate() in D:\a\1\s\cs\cs\ObjectPool.cs:line 152
...
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Question here is that, shouldn't GetOrCreate() thread safe? Does this method do anything on the input file?

Please let me know. Thanks a lot.

**Comment by hsinyij** [comment]
After I debugged more, I feel it may be the dispose() issue. It seems that the dispose() does not release the file lock. Please let me know. Thanks a lot.

**Comment by JohnLangford** [comment]
@eisber could this be related to the segfault you are debugging?

**Comment by eisber** [comment]
a) I'd recommend you pass the model in using MemorySteam or FileStream
b) you really need to Dispose properly otherwise you have open files and memory left over

**Comment by JohnLangford** [comment]
I believe this is addressed so closing.  Reopen if not.  Thanks @eisber
