### ISSUE TITLE
develop --no-deps" failed with error code 1 in

### ISSUE THREAD

**Issue by wa1618i** [JohnLangford/vowpal_wabbit#1266]
I have installed all pre-requisite packcages in Ubuntu 14.04. After that...
cd vowpal_wabbit then make, then make test, then sudo -i, then make install...ALL clean no error
But then when cd vowpal_wabbit/python pip install -e .   it throws error:

lemma@Lemma:~/vowpal_wabbit/python$ pip install -e .
Obtaining file:///home/lemma/vowpal_wabbit/python
Installing collected packages: vowpalwabbit
  Running setup.py develop for vowpalwabbit
    Complete output from command /home/lemma/miniconda2/bin/python -c "import setuptools, tokenize;__file__='/home/lemma/vowpal_wabbit/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing vowpalwabbit.egg-info/PKG-INFO
    writing top-level names to vowpalwabbit.egg-info/top_level.txt
    writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.dll' under directory 'bin'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    running build_ext
    cd vowpalwabbit; make -j 4 things
    make[1]: Entering directory `/home/lemma/vowpal_wabbit/python/src/vowpalwabbit'
    make[1]: Nothing to be done for `things'.
    make[1]: Leaving directory `/home/lemma/vowpal_wabbit/python/src/vowpalwabbit'
    cd python; make things
    Using Python 2.7
    make[1]: python2.7-config: Command not found
    make[1]: Entering directory `/home/lemma/vowpal_wabbit/python/src/python'
    /usr/bin/g++ -std=c++0x  -I /usr/include -I ../rapidjson/include -fPIC -c pylibvw.cc -o pylibvw.o
    In file included from /usr/include/boost/python/detail/prefix.hpp:13:0,
                     from /usr/include/boost/python/args.hpp:8,
                     from /usr/include/boost/python.hpp:11,
                     from pylibvw.cc:11:
    /usr/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
     # include <pyconfig.h>
                           ^
    compilation terminated.
    make[1]: *** [pylibvw.o] Error 1
    make[1]: Leaving directory `/home/lemma/vowpal_wabbit/python/src/python'
    make: *** [python] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/lemma/vowpal_wabbit/python/setup.py", line 209, in <module>
        tests_require=['tox']
      File "/home/lemma/miniconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/lemma/miniconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/lemma/miniconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/lemma/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/develop.py", line 34, in run
      File "/home/lemma/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/develop.py", line 119, in install_for_development
      File "/home/lemma/miniconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/lemma/miniconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/lemma/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/build_ext.py", line 77, in run
      File "/home/lemma/miniconda2/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
        _build_ext.build_ext.run(self)
      File "/home/lemma/miniconda2/lib/python2.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/lemma/miniconda2/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
        self.build_extension(ext)
      File "/home/lemma/vowpal_wabbit/python/setup.py", line 120, in build_extension
        subprocess.check_call(['make', 'python'], cwd=path.join(here, 'src'), env=env)
      File "/home/lemma/miniconda2/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'python']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/home/lemma/miniconda2/bin/python -c "import setuptools, tokenize;__file__='/home/lemma/vowpal_wabbit/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/lemma/vowpal_wabbit/python/

I'm not sure what went wrong in my machine or the package?

**Comment by JohnLangford** [comment]
I'm not sure.  @gramhagen any ideas?

**Comment by Scott-Graham-Bose** [comment]
could be a few things:
```make[1]: python2.7-config: Command not found```
seems to indicate there is no executable python2.7-config file in /home/lemma/miniconda2/bin, is that the case?

also:
```
/usr/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
```
looks like it's failing to find the python header files, with ubuntu you can install these dependencies with
```
sudo apt-get install python-dev
```

i would try installing python-dev first, and retry, if not you may want to look at the conda instructions here to see if that can help: https://github.com/JohnLangford/vowpal_wabbit#osx-python-binding-installation-with-anaconda

**Comment by wa1618i** [comment]
Thank you, installing the python-dev solved the issue :)
