### ISSUE TITLE
Mac installation issue 

### ISSUE THREAD

**Issue by madhancr** [JohnLangford/vowpal_wabbit#1386]
Hello, I am getting this error on Mac 10.13.2, Python 3.6.4 :: Anaconda, Inc.
(make in parent dir went through without errors)

$python setup.py install
running install
running bdist_egg
running egg_info
writing vowpalwabbit.egg-info/PKG-INFO
writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
writing top-level names to vowpalwabbit.egg-info/top_level.txt
reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.dll' under directory 'bin'
warning: no previously-included files matching '*.exe' found anywhere in distribution
writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/madhan/Dev/Fellowship_AI/vowpal_wabbit/missing aclocal-1.15 -I acinclude.d
aclocal-1.15: warning: couldn't open directory 'acinclude.d': No such file or directory
 cd . && /bin/sh /Users/madhan/Dev/Fellowship_AI/vowpal_wabbit/missing automake-1.15 --foreign
configure.ac:2: error: required file 'vowpalwabbit/config.h.in' not found
configure.ac:83: error: required file 'vowpalwabbit/Makefile.in' not found
configure.ac:83: error: required file 'cluster/Makefile.in' not found
Makefile.am:1: error: required directory ./vowpalwabbit does not exist
Makefile.am:1: error: required directory ./cluster does not exist
make: *** [Makefile.in] Error 1
Traceback (most recent call last):
  File "setup.py", line 209, in <module>
    tests_require=['tox']
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 169, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 155, in call_command
    self.run_command(cmdname)
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "setup.py", line 127, in build
    _install_lib.build(self)
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
    _build_ext.run(self)
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 120, in build_extension
    subprocess.check_call(['make', 'python'], cwd=path.join(here, 'src'), env=env)
  File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'python']' returned non-zero exit status 2.

**Comment by gramhagen** [comment]
is this the same issue as #1387 ?

**Comment by JohnLangford** [comment]
Closing given lack of response, please reopen if this persists.  Thanks @gramhagen
