### ISSUE TITLE
 run on Hadoop clusters failed

### ISSUE THREAD

**Issue by limtymz** [JohnLangford/vowpal_wabbit#955]
Help, Thanks!

1. the directory for running:
`/vowpal_wabbit/vowpalwabbit`

2. the process of "spanning_tree " is running
`mzsip    27735  0.0  0.0 103236   896 pts/2    S+   11:35   0:00 grep spanning_tree`

3. cmd:
`hadoop jar $HADOOP_HOME/share/hadoop/tools/lib/hadoop-streaming-2.4.1.jar -Dmapred.job.map.memory.mb=2500 -input <input> -output <output> -file vw -file runvw.sh -mapper runvw.sh -reducer NONE`

4. error:
`16/02/29 11:21:56 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
packageJobJar: [vw, runvw.sh, /hadoop/data01/tmp/mzsip/hadoop-unjar2932847810632473163/] [] /tmp/streamjob3730049061838382777.jar tmpDir=null
16/02/29 11:21:57 INFO client.RMProxy: Connecting to ResourceManager at hd-nn-1.zhuzhu.gz/10.3.161.73:8032
16/02/29 11:21:58 INFO client.RMProxy: Connecting to ResourceManager at hd-nn-1.zhuzhu.gz/10.3.161.73:8032
16/02/29 11:21:58 INFO lzo.GPLNativeCodeLoader: Loaded native gpl library from the embedded binaries
16/02/29 11:21:58 INFO lzo.LzoCodec: Successfully loaded & initialized native-lzo library [hadoop-lzo rev 478aa845e11bbbeeb9b8326e733cd20a06d2cb3a]
16/02/29 11:21:58 INFO mapred.FileInputFormat: Total input paths to process : 2
16/02/29 11:21:59 INFO mapreduce.JobSubmitter: number of splits:2
16/02/29 11:21:59 INFO Configuration.deprecation: mapred.job.map.memory.mb is deprecated. Instead, use mapreduce.map.memory.mb
16/02/29 11:21:59 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1454400113226_162819
16/02/29 11:21:59 INFO impl.YarnClientImpl: Submitted application application_1454400113226_162819
16/02/29 11:21:59 INFO mapreduce.Job: The url to track the job: http://hd-nn-1.zhuzhu.gz:8088/proxy/application_1454400113226_162819/
16/02/29 11:21:59 INFO mapreduce.Job: Running job: job_1454400113226_162819
16/02/29 11:22:05 INFO mapreduce.Job: Job job_1454400113226_162819 running in uber mode : false
16/02/29 11:22:05 INFO mapreduce.Job:  map 0% reduce 0%
16/02/29 11:22:09 INFO mapreduce.Job: Task Id : attempt_1454400113226_162819_m_000001_0, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:430)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:167)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)

16/02/29 11:22:11 INFO mapreduce.Job: Task Id : attempt_1454400113226_162819_m_000000_0, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:430)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:167)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)

16/02/29 11:22:15 INFO mapreduce.Job: Task Id : attempt_1454400113226_162819_m_000001_1, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:430)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:167)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)

16/02/29 11:22:16 INFO mapreduce.Job: Task Id : attempt_1454400113226_162819_m_000000_1, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:430)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:167)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)

16/02/29 11:22:20 INFO mapreduce.Job: Task Id : attempt_1454400113226_162819_m_000001_2, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:430)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:167)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)

16/02/29 11:22:22 INFO mapreduce.Job: Task Id : attempt_1454400113226_162819_m_000000_2, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:430)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:167)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)

16/02/29 11:22:25 INFO mapreduce.Job:  map 100% reduce 0%
16/02/29 11:22:26 INFO mapreduce.Job: Job job_1454400113226_162819 failed with state FAILED due to: Task failed task_1454400113226_162819_m_000001
Job failed as tasks failed. failedMaps:1 failedReduces:0

16/02/29 11:22:27 INFO mapreduce.Job: Counters: 13
	Job Counters 
		Failed map tasks=7
		Killed map tasks=1
		Launched map tasks=8
		Other local map tasks=6
		Rack-local map tasks=2
		Total time spent by all maps in occupied slots (ms)=28677
		Total time spent by all reduces in occupied slots (ms)=0
		Total time spent by all map tasks (ms)=28677
		Total vcore-seconds taken by all map tasks=28677
		Total megabyte-seconds taken by all map tasks=71692500
	Map-Reduce Framework
		CPU time spent (ms)=0
		Physical memory (bytes) snapshot=0
		Virtual memory (bytes) snapshot=0
16/02/29 11:22:27 ERROR streaming.StreamJob: Job not Successful!
Streaming Command Failed!`

**Comment by JohnLangford** [comment]
Usually, this means something like "Hadoop killed the VW instance 
because it was taking more RAM than the default limit allowed".

Try getting any script working in the mapper, then start adding to it 
until you have what you want.  (And debug with the script output.)

-Jon

**Comment by limtymz** [comment]
Thank you very much for response.
However, the total size of training files is less than 50M.....
I am a newbie, can you give me a simplest example  (cmd/script) for classification using logistic regression and SGD?

**Comment by JohnLangford** [comment]
Then your script is probably dieing because the environment variables on 
Hadoop are different than are expected.  You need to debug that script 
yourself.

Also, with 50MB, why are you bothering with Hadoop?

-John
